import 'package:flutter_project_template_firebase/gen/assets.gen.dart';
import 'package:flutter_project_template_firebase/models/team_model.dart';

final nhlTeams = [
  Team(
    id: '1',
    teamName: 'Anaheim Ducks',
    largeLogo: Assets.icons.anaheimDucksLarge.path,
    smallLogol: Assets.icons.anaheimDucksSmall.path,
    primaryColor: '0xFFF47A38',
    secondaryColor: '0xFFB9975B',
  ),
  Team(
    id: '2',
    teamName: 'Arizona Coyotes',
    largeLogo: Assets.icons.arizonaCoyotesLarge.path,
    smallLogol: Assets.icons.arizonaCoyotesLarge.path,
    primaryColor: '0xFF862633',
    secondaryColor: '0xFFDDCBA4',
  ),
  Team(
    id: '3',
    teamName: 'Boston Bruins',
    largeLogo: Assets.icons.bostonBruinsLarge.path,
    smallLogol: Assets.icons.bostonBruinsLarge.path,
    primaryColor: '0xFFF47A38',
    secondaryColor: '0xFF010101',
  ),
  Team(
    id: '4',
    teamName: 'Buffalo Sabres',
    largeLogo: Assets.icons.buffaloSabresLarge.path,
    smallLogol: Assets.icons.buffaloSabresSmall.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFFFB81C',
  ),
  Team(
    id: '5',
    teamName: 'Calgary Flames',
    largeLogo: Assets.icons.calgaryFlamesLarge.path,
    smallLogol: Assets.icons.calgaryFlamesSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFFF1BE48',
  ),
  Team(
    id: '6',
    teamName: 'Carolina Hurricanes',
    largeLogo: Assets.icons.carolinaHurricanesLarge.path,
    smallLogol: Assets.icons.carolinaHurricanesLarge.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF010101',
  ),
  Team(
    id: '7',
    teamName: 'Chicago Blackhawks',
    largeLogo: Assets.icons.chicagoBlackhawksLarge.path,
    smallLogol: Assets.icons.chicagoBlackhawksSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFFFFD100',
  ),
  Team(
    id: '8',
    teamName: 'Colorado Avalanche',
    largeLogo: Assets.icons.coloradoAvalancheLarge.path,
    smallLogol: Assets.icons.coloradoAvalancheSmall.path,
    primaryColor: '0xFF6F263D',
    secondaryColor: '0xFF236192',
  ),
  Team(
    id: '9',
    teamName: 'Columbus Blue Jackets',
    largeLogo: Assets.icons.colombusBlueJacketsLarge.path,
    smallLogol: Assets.icons.colombusBlueJacketsSmall.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFC8102E',
  ),
  Team(
    id: '10',
    teamName: 'Dallas Stars',
    largeLogo: Assets.icons.dallasStarsLarge.path,
    smallLogol: Assets.icons.dallasStarsSmall.path,
    primaryColor: '0xFF006341',
    secondaryColor: '0xFFFFFFFF',
  ),
  Team(
    id: '11',
    teamName: 'Detroit Red Wings',
    largeLogo: Assets.icons.detroitRedWingsLarge.path,
    smallLogol: Assets.icons.detroitRedWingsLarge.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFFFFFFFF',
  ),
  Team(
    id: '12',
    teamName: 'Edmonton Oilers',
    largeLogo: Assets.icons.edmontonOilersLarge.path,
    smallLogol: Assets.icons.edmontonOilersLarge.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFFC4C02',
  ),
  Team(
    id: '13',
    teamName: 'Florida Panthers',
    largeLogo: Assets.icons.floridaPanthersLarge.path,
    smallLogol: Assets.icons.floridaPanthersLarge.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF041E42',
  ),
  Team(
    id: '14',
    teamName: 'Los Angeles Kings',
    largeLogo: Assets.icons.losAngelesLarge.path,
    smallLogol: Assets.icons.losAngelesKingsSmall.path,
    primaryColor: '0xFFA2AAAD',
    secondaryColor: '0xFF010101',
  ),
  Team(
    id: '15',
    teamName: 'Minnesota Wild',
    largeLogo: Assets.icons.minnesotaWildLarge.path,
    smallLogol: Assets.icons.minnesotaWildLarge.path,
    primaryColor: '0xFF154734',
    secondaryColor: '0xFFA6192E',
  ),
  Team(
    id: '16',
    teamName: 'Montreal Canadiens',
    largeLogo: Assets.icons.montrealCanadiens.path,
    smallLogol: Assets.icons.montrealCanadiensSmall.path,
    primaryColor: '0xFFA6192E',
    secondaryColor: '0xFFFFFFFF',
  ),
  Team(
    id: '17',
    teamName: 'Nashville Predators',
    largeLogo: Assets.icons.nashvillePredatorsLarge.path,
    smallLogol: Assets.icons.nashvillePredatorsSmall.path,
    primaryColor: '0xFFFFB81C',
    secondaryColor: '0xFF041E42',
  ),
  Team(
    id: '18',
    teamName: 'New Jersey Devils',
    largeLogo: Assets.icons.newJerseyDevilsLarge.path,
    smallLogol: Assets.icons.newJerseyDevilsSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF010101',
  ),
  Team(
    id: '19',
    teamName: 'New York Islanders',
    largeLogo: Assets.icons.newYorkIslandersLarge.path,
    smallLogol: Assets.icons.newYorkIslandersSmall.path,
    primaryColor: '0xFF003087',
    secondaryColor: '0xFFFC4C02',
  ),
  Team(
    id: '20',
    teamName: 'New York Rangers',
    largeLogo: Assets.icons.newYorkRangersLarge.path,
    smallLogol: Assets.icons.newYorkRangersSmall.path,
    primaryColor: '0xFF0033A0',
    secondaryColor: '0xFFC8102E',
  ),
  Team(
    id: '21',
    teamName: 'Ottawa Senators',
    largeLogo: Assets.icons.ottawaSenatorsLarge.path,
    smallLogol: Assets.icons.ottawaSenatorsSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF010101',
  ),
  Team(
    id: '22',
    teamName: 'Philadelphia Flyers',
    largeLogo: Assets.icons.philadelphiaFlyersLarge.path,
    smallLogol: Assets.icons.philadelphiaFlyersSmall.path,
    primaryColor: '0xFFFA4616',
    secondaryColor: '0xFF010101',
  ),
  Team(
    id: '23',
    teamName: 'Pittsburgh Penguins',
    largeLogo: Assets.icons.pittsburghPenguinsLarge.path,
    smallLogol: Assets.icons.pittsburghPenguinsSmall.path,
    primaryColor: '0xFFFFB81C',
    secondaryColor: '0xFF010101',
  ),
  Team(
    id: '24',
    teamName: 'San Jose Sharks',
    largeLogo: Assets.icons.sanJoseSharksLarge.path,
    smallLogol: Assets.icons.sanJoseSharksSmall.path,
    primaryColor: '0xFF006272',
    secondaryColor: '0xFFE57200',
  ),
  Team(
    id: '25',
    teamName: 'Seattle Kraken',
    largeLogo: Assets.icons.seattleKrakenLarge.path,
    smallLogol: Assets.icons.seattleKrakenSmall.path,
    primaryColor: '0xFF001628',
    secondaryColor: '0xFF629EB5',
  ),
  Team(
    id: '26',
    teamName: 'St. Louis Blues',
    largeLogo: Assets.icons.stLouisBluesLarge.path,
    smallLogol: Assets.icons.stLouisBluesSmall.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFFFB81C',
  ),
  Team(
    id: '27',
    teamName: 'Tampa Bay Lightning',
    largeLogo: Assets.icons.tampaBayLightningLarge.path,
    smallLogol: Assets.icons.tampaBayLightningSmall.path,
    primaryColor: '0xFF00205B',
    secondaryColor: '0xFFFFFFFF',
  ),
  Team(
    id: '28',
    teamName: 'Toronto Maple Leafs',
    largeLogo: Assets.icons.torontoMapleLeafsLarge.path,
    smallLogol: Assets.icons.torontoMapleLeafsSmall.path,
    primaryColor: '0xFF00205B',
    secondaryColor: '0xFFFFFFFF',
  ),
  Team(
    id: '29',
    teamName: 'Vancouver Canucks',
    largeLogo: Assets.icons.vancouverCanucksLarge.path,
    smallLogol: Assets.icons.vancouverCanucksSmall.path,
    primaryColor: '0xFF00205B',
    secondaryColor: '0xFFFFFFFF',
  ),
  Team(
    id: '30',
    teamName: 'Vegas Golden Knights',
    largeLogo: Assets.icons.vegasGoldenKnightsLarge.path,
    smallLogol: Assets.icons.vegasGoldenKnightsSmall.path,
    primaryColor: '0xFFB9975B',
    secondaryColor: '0xFF333F48',
  ),
  Team(
    id: '31',
    teamName: 'Washington Capitals',
    largeLogo: Assets.icons.washingtonCapitalsLarge.path,
    smallLogol: Assets.icons.washingtonCapitalsSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF041E42',
  ),
  Team(
    id: '32',
    teamName: 'Winnipeg Jets',
    largeLogo: Assets.icons.winnipegJetsLarge.path,
    smallLogol: Assets.icons.winnipegJetsSmall.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFFFFFFF',
  ),
];
