import 'package:flutter/material.dart';
import 'package:flutter_project_template_firebase/gen/assets.gen.dart';
import 'package:flutter_project_template_firebase/models/team_model.dart';

final nhlTeams = [
  Team(
    id: '1',
    teamName: 'Anaheim Ducks',
    largeLogo: Assets.icons.anaheimDucksLarge.svg(),
    smallLogol: Assets.icons.anaheimDucksSmall.svg(),
    primaryColor: const Color(0xFFF47A38),
    secondaryColor: const Color(0xFFB9975B),
  ),
  Team(
    id: '2',
    teamName: 'Arizona Coyotes',
    largeLogo: Assets.icons.arizonaCoyotesLarge.svg(),
    smallLogol: Assets.icons.arizonaCoyotesLarge.svg(),
    primaryColor: const Color(0xFF862633),
    secondaryColor: const Color(0xFFDDCBA4),
  ),
  Team(
    id: '3',
    teamName: 'Boston Bruins',
    largeLogo: Assets.icons.bostonBruinsLarge.svg(),
    smallLogol: Assets.icons.bostonBruinsLarge.svg(),
    primaryColor: const Color(0xFFF47A38),
    secondaryColor: const Color(0xFF010101),
  ),
  Team(
    id: '4',
    teamName: 'Buffalo Sabres',
    largeLogo: Assets.icons.buffaloSabresLarge.svg(),
    smallLogol: Assets.icons.buffaloSabresSmall.svg(),
    primaryColor: const Color(0xFF041E42),
    secondaryColor: const Color(0xFFFFB81C),
  ),
  Team(
    id: '5',
    teamName: 'Calgary Flames',
    largeLogo: Assets.icons.calgaryFlamesLarge.svg(),
    smallLogol: Assets.icons.calgaryFlamesSmall.svg(),
    primaryColor: const Color(0xFFC8102E),
    secondaryColor: const Color(0xFFF1BE48),
  ),
  Team(
    id: '6',
    teamName: 'Carolina Hurricanes',
    largeLogo: Assets.icons.carolinaHurricanesLarge.svg(),
    smallLogol: Assets.icons.carolinaHurricanesLarge.svg(),
    primaryColor: const Color(0xFFC8102E),
    secondaryColor: const Color(0xFF010101),
  ),
  Team(
    id: '7',
    teamName: 'Chicago Blackhawks',
    largeLogo: Assets.icons.chicagoBlackhawksLarge.svg(),
    smallLogol: Assets.icons.chicagoBlackhawksSmall.svg(),
    primaryColor: const Color(0xFFC8102E),
    secondaryColor: const Color(0xFFFFD100),
  ),
  Team(
    id: '8',
    teamName: 'Colorado Avalanche',
    largeLogo: Assets.icons.coloradoAvalancheLarge.svg(),
    smallLogol: Assets.icons.coloradoAvalancheSmall.svg(),
    primaryColor: const Color(0xFF6F263D),
    secondaryColor: const Color(0xFF236192),
  ),
  Team(
    id: '9',
    teamName: 'Columbus Blue Jackets',
    largeLogo: Assets.icons.colombusBlueJacketsLarge.svg(),
    smallLogol: Assets.icons.colombusBlueJacketsSmall.svg(),
    primaryColor: const Color(0xFF041E42),
    secondaryColor: const Color(0xFFC8102E),
  ),
  Team(
    id: '10',
    teamName: 'Dallas Stars',
    largeLogo: Assets.icons.dallasStarsLarge.svg(),
    smallLogol: Assets.icons.dallasStarsSmall.svg(),
    primaryColor: const Color(0xFF006341),
    secondaryColor: const Color(0xFFFFFFFF),
  ),
  Team(
    id: '11',
    teamName: 'Detroit Red Wings',
    largeLogo: Assets.icons.detroitRedWingsLarge.svg(),
    smallLogol: Assets.icons.detroitRedWingsLarge.svg(),
    primaryColor: const Color(0xFFC8102E),
    secondaryColor: const Color(0xFFFFFFFF),
  ),
  Team(
    id: '12',
    teamName: 'Edmonton Oilers',
    largeLogo: Assets.icons.edmontonOilersLarge.svg(),
    smallLogol: Assets.icons.edmontonOilersLarge.svg(),
    primaryColor: const Color(0xFF041E42),
    secondaryColor: const Color(0xFFFC4C02),
  ),
  Team(
    id: '13',
    teamName: 'Florida Panthers',
    largeLogo: Assets.icons.floridaPanthersLarge.svg(),
    smallLogol: Assets.icons.floridaPanthersLarge.svg(),
    primaryColor: const Color(0xFFC8102E),
    secondaryColor: const Color(0xFF041E42),
  ),
  Team(
    id: '14',
    teamName: 'Los Angeles Kings',
    largeLogo: Assets.icons.losAngelesLarge.svg(),
    smallLogol: Assets.icons.losAngelesKingsSmall.svg(),
    primaryColor: const Color(0xFFA2AAAD),
    secondaryColor: const Color(0xFF010101),
  ),
  Team(
    id: '15',
    teamName: 'Minnesota Wild',
    largeLogo: Assets.icons.minnesotaWildLarge.svg(),
    smallLogol: Assets.icons.minnesotaWildLarge.svg(),
    primaryColor: const Color(0xFF154734),
    secondaryColor: const Color(0xFFA6192E),
  ),
  Team(
    id: '16',
    teamName: 'Montreal Canadiens',
    largeLogo: Assets.icons.montrealCanadiens.svg(),
    smallLogol: Assets.icons.montrealCanadiensSmall.svg(),
    primaryColor: const Color(0xFFA6192E),
    secondaryColor: const Color(0xFFFFFFFF),
  ),
  Team(
    id: '17',
    teamName: 'Nashville Predators',
    largeLogo: Assets.icons.nashvillePredatorsLarge.svg(),
    smallLogol: Assets.icons.nashvillePredatorsSmall.svg(),
    primaryColor: const Color(0xFFFFB81C),
    secondaryColor: const Color(0xFF041E42),
  ),
  Team(
    id: '18',
    teamName: 'New Jersey Devils',
    largeLogo: Assets.icons.newJerseyDevilsLarge.svg(),
    smallLogol: Assets.icons.newJerseyDevilsSmall.svg(),
    primaryColor: const Color(0xFFC8102E),
    secondaryColor: const Color(0xFF010101),
  ),
  Team(
    id: '19',
    teamName: 'New York Islanders',
    largeLogo: Assets.icons.newYorkIslandersLarge.svg(),
    smallLogol: Assets.icons.newYorkIslandersSmall.svg(),
    primaryColor: const Color(0xFF003087),
    secondaryColor: const Color(0xFFFC4C02),
  ),
  Team(
    id: '20',
    teamName: 'New York Rangers',
    largeLogo: Assets.icons.newYorkRangersLarge.svg(),
    smallLogol: Assets.icons.newYorkRangersSmall.svg(),
    primaryColor: const Color(0xFF0033A0),
    secondaryColor: const Color(0xFFC8102E),
  ),
  Team(
    id: '21',
    teamName: 'Ottawa Senators',
    largeLogo: Assets.icons.ottawaSenatorsLarge.svg(),
    smallLogol: Assets.icons.ottawaSenatorsSmall.svg(),
    primaryColor: const Color(0xFFC8102E),
    secondaryColor: const Color(0xFF010101),
  ),
  Team(
    id: '22',
    teamName: 'Philadelphia Flyers',
    largeLogo: Assets.icons.philadelphiaFlyersLarge.svg(),
    smallLogol: Assets.icons.philadelphiaFlyersSmall.svg(),
    primaryColor: const Color(0xFFFA4616),
    secondaryColor: const Color(0xFF010101),
  ),
  Team(
    id: '23',
    teamName: 'Pittsburgh Penguins',
    largeLogo: Assets.icons.pittsburghPenguinsLarge.svg(),
    smallLogol: Assets.icons.pittsburghPenguinsSmall.svg(),
    primaryColor: const Color(0xFFFFB81C),
    secondaryColor: const Color(0xFF010101),
  ),
  Team(
    id: '24',
    teamName: 'San Jose Sharks',
    largeLogo: Assets.icons.sanJoseSharksLarge.svg(),
    smallLogol: Assets.icons.sanJoseSharksSmall .svg(),
    primaryColor: const Color(0xFF006272),
    secondaryColor: const Color(0xFFE57200),
  ),
  Team(
    id: '25',
    teamName: 'Seattle Kraken',
    largeLogo: Assets.icons.seattleKrakenLarge.svg(),
    smallLogol: Assets.icons.seattleKrakenSmall.svg(),
    primaryColor: const Color(0xFF001628),
    secondaryColor: const Color(0xFF629EB5),
  ),
  Team(
    id: '26',
    teamName: 'St. Louis Blues',
    largeLogo: Assets.icons.stLouisBluesLarge.svg(),
    smallLogol: Assets.icons.stLouisBluesSmall.svg(),
    primaryColor: const Color(0xFF041E42),
    secondaryColor: const Color(0xFFFFB81C),
  ),
  Team(
    id: '27',
    teamName: 'Tampa Bay Lightning',
    largeLogo: Assets.icons.tampaBayLightningLarge.svg(),
    smallLogol: Assets.icons.tampaBayLightningSmall.svg(),
    primaryColor: const Color(0xFF00205B),
    secondaryColor: const Color(0xFFFFFFFF),
  ),
  Team(
    id: '28',
    teamName: 'Toronto Maple Leafs',
    largeLogo: Assets.icons.torontoMapleLeafsLarge.svg(),
    smallLogol: Assets.icons.torontoMapleLeafsSmall.svg(),
    primaryColor: const Color(0xFF00205B),
    secondaryColor: const Color(0xFFFFFFFF),
  ),
  Team(
    id: '29',
    teamName: 'Vancouver Canucks',
    largeLogo: Assets.icons.vancouverCanucksLarge.svg(),
    smallLogol: Assets.icons.vancouverCanucksSmall.svg(),
    primaryColor: const Color(0xFF00205B),
    secondaryColor: const Color(0xFFFFFFFF),
  ),
  Team(
    id: '30',
    teamName: 'Vegas Golden Knights',
    largeLogo: Assets.icons.vegasGoldenKnightsLarge.svg(),
    smallLogol: Assets.icons.vegasGoldenKnightsSmall.svg(),
    primaryColor: const Color(0xFFB9975B),
    secondaryColor: const Color(0xFF333F48),
  ),
  Team(
    id: '31',
    teamName: 'Washington Capitals',
    largeLogo: Assets.icons.washingtonCapitalsLarge.svg(),
    smallLogol: Assets.icons.washingtonCapitalsSmall.svg(),
    primaryColor: const Color(0xFFC8102E),
    secondaryColor: const Color(0xFF041E42),
  ),
  Team(
    id: '32',
    teamName: 'Winnipeg Jets',
    largeLogo: Assets.icons.winnipegJetsLarge.svg(),
    smallLogol: Assets.icons.winnipegJetsSmall.svg(),
    primaryColor: const Color(0xFF041E42),
    secondaryColor: const Color(0xFFFFFFFF),
  ),
];
