import 'package:hockey_mob/gen/assets.gen.dart';
import 'package:hockey_mob/models/team_model.dart';

final nhlTeams = [
  Team(
    id: 1,
    combinedName: 'Anaheim Ducks',
    largeLogo: Assets.icons.anaheimDucksLarge.path,
    smallLogol: Assets.icons.anaheimDucksSmall.path,
    primaryColor: '0xFFF47A38',
    secondaryColor: '0xFFB9975B',
    teamLocation: 'Anaheim',
    teamName: 'Ducks',
    teamAbr: 'ANA',
  ),
  Team(
    id: 2,
    combinedName: 'Arizona Coyotes',
    largeLogo: Assets.icons.arizonaCoyotesLarge.path,
    smallLogol: Assets.icons.arizonaCoyotesLarge.path,
    primaryColor: '0xFF862633',
    secondaryColor: '0xFFDDCBA4',
    teamLocation: 'Arizona',
    teamName: 'Coyotes',
    teamAbr: 'ARI',
  ),
  Team(
    id: 3,
    combinedName: 'Boston Bruins',
    largeLogo: Assets.icons.bostonBruinsLarge.path,
    smallLogol: Assets.icons.bostonBruinsLarge.path,
    primaryColor: '0xFFF47A38',
    secondaryColor: '0xFF010101',
    teamLocation: 'Boston',
    teamName: 'Bruins',
    teamAbr: 'BOS',
  ),
  Team(
    id: 4,
    combinedName: 'Buffalo Sabres',
    largeLogo: Assets.icons.buffaloSabresLarge.path,
    smallLogol: Assets.icons.buffaloSabresSmall.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFFFB81C',
    teamLocation: 'Buffalo',
    teamName: 'Sabres',
    teamAbr: 'BUF',
  ),
  Team(
    id: 5,
    combinedName: 'Calgary Flames',
    largeLogo: Assets.icons.calgaryFlamesLarge.path,
    smallLogol: Assets.icons.calgaryFlamesSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFFF1BE48',
    teamLocation: 'Calgary',
    teamName: 'Flames',
    teamAbr: 'CGY',
  ),
  Team(
    id: 6,
    combinedName: 'Carolina Hurricanes',
    largeLogo: Assets.icons.carolinaHurricanesLarge.path,
    smallLogol: Assets.icons.carolinaHurricanesLarge.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF010101',
    teamLocation: 'Carolina',
    teamName: 'Hurricanes',
    teamAbr: 'CAR',
  ),
  Team(
    id: 7,
    combinedName: 'Chicago Blackhawks',
    largeLogo: Assets.icons.chicagoBlackhawksLarge.path,
    smallLogol: Assets.icons.chicagoBlackhawksSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFFFFD100',
    teamLocation: 'Chicago',
    teamName: 'Blackhawks',
    teamAbr: 'CHI',
  ),
  Team(
    id: 8,
    combinedName: 'Colorado Avalanche',
    largeLogo: Assets.icons.coloradoAvalancheLarge.path,
    smallLogol: Assets.icons.coloradoAvalancheSmall.path,
    primaryColor: '0xFF6F263D',
    secondaryColor: '0xFF236192',
    teamLocation: 'Colorado',
    teamName: 'Avalanche',
    teamAbr: 'COL',
  ),
  Team(
    id: 9,
    combinedName: 'Columbus Blue Jackets',
    largeLogo: Assets.icons.colombusBlueJacketsLarge.path,
    smallLogol: Assets.icons.colombusBlueJacketsSmall.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFC8102E',
    teamLocation: 'Columbus',
    teamName: 'Blue Jackets',
    teamAbr: 'CBJ',
  ),
  Team(
    id: 10,
    combinedName: 'Dallas Stars',
    largeLogo: Assets.icons.dallasStarsLarge.path,
    smallLogol: Assets.icons.dallasStarsSmall.path,
    primaryColor: '0xFF006341',
    secondaryColor: '0xFFFFFFFF',
    teamLocation: 'Dallas',
    teamName: 'Stars',
    teamAbr: 'DAL',
  ),
  Team(
    id: 11,
    combinedName: 'Detroit Red Wings',
    largeLogo: Assets.icons.detroitRedWingsLarge.path,
    smallLogol: Assets.icons.detroitRedWingsLarge.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFFFFFFFF',
    teamLocation: 'Detroit',
    teamName: 'Red Wings',
    teamAbr: 'DET',
  ),
  Team(
    id: 12,
    combinedName: 'Edmonton Oilers',
    largeLogo: Assets.icons.edmontonOilersLarge.path,
    smallLogol: Assets.icons.edmontonOilersLarge.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFFC4C02',
    teamLocation: 'Edmonton',
    teamName: 'Oilers',
    teamAbr: 'EDM',
  ),
  Team(
    id: 13,
    combinedName: 'Florida Panthers',
    largeLogo: Assets.icons.floridaPanthersLarge.path,
    smallLogol: Assets.icons.floridaPanthersLarge.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF041E42',
    teamLocation: 'Florida',
    teamName: 'Panthers',
    teamAbr: 'FLA',
  ),
  Team(
    id: 14,
    combinedName: 'Los Angeles Kings',
    largeLogo: Assets.icons.losAngelesLarge.path,
    smallLogol: Assets.icons.losAngelesKingsSmall.path,
    primaryColor: '0xFFA2AAAD',
    secondaryColor: '0xFF010101',
    teamLocation: 'Los Angeles',
    teamName: 'Kings',
    teamAbr: 'LA',
  ),
  Team(
    id: 15,
    combinedName: 'Minnesota Wild',
    largeLogo: Assets.icons.minnesotaWildLarge.path,
    smallLogol: Assets.icons.minnesotaWildLarge.path,
    primaryColor: '0xFF154734',
    secondaryColor: '0xFFA6192E',
    teamLocation: 'Minnesota',
    teamName: 'Wild',
    teamAbr: 'MIN',
  ),
  Team(
    id: 16,
    combinedName: 'Montreal Canadiens',
    largeLogo: Assets.icons.montrealCanadiens.path,
    smallLogol: Assets.icons.montrealCanadiensSmall.path,
    primaryColor: '0xFFA6192E',
    secondaryColor: '0xFFFFFFFF',
    teamLocation: 'Montreal',
    teamName: 'Canadiens',
    teamAbr: 'MTL',
  ),
  Team(
    id: 17,
    combinedName: 'Nashville Predators',
    largeLogo: Assets.icons.nashvillePredatorsLarge.path,
    smallLogol: Assets.icons.nashvillePredatorsSmall.path,
    primaryColor: '0xFFFFB81C',
    secondaryColor: '0xFF041E42',
    teamLocation: 'Nashville',
    teamName: 'Predators',
    teamAbr: 'NSH',
  ),
  Team(
    id: 18,
    combinedName: 'New Jersey Devils',
    largeLogo: Assets.icons.newJerseyDevilsLarge.path,
    smallLogol: Assets.icons.newJerseyDevilsSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF010101',
    teamLocation: 'New Jersey',
    teamName: 'Devils',
    teamAbr: 'NJ',
  ),
  Team(
    id: 19,
    combinedName: 'New York Islanders',
    largeLogo: Assets.icons.newYorkIslandersLarge.path,
    smallLogol: Assets.icons.newYorkIslandersSmall.path,
    primaryColor: '0xFF003087',
    secondaryColor: '0xFFFC4C02',
    teamLocation: 'New York',
    teamName: 'Islanders',
    teamAbr: 'NYI',
  ),
  Team(
    id: 20,
    combinedName: 'New York Rangers',
    largeLogo: Assets.icons.newYorkRangersLarge.path,
    smallLogol: Assets.icons.newYorkRangersSmall.path,
    primaryColor: '0xFF0033A0',
    secondaryColor: '0xFFC8102E',
    teamLocation: 'New York',
    teamName: 'Rangers',
    teamAbr: 'NYR',
  ),
  Team(
    id: 21,
    combinedName: 'Ottawa Senators',
    largeLogo: Assets.icons.ottawaSenatorsLarge.path,
    smallLogol: Assets.icons.ottawaSenatorsSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF010101',
    teamLocation: 'Ottawa',
    teamName: 'Senators',
    teamAbr: 'OTT',
  ),
  Team(
    id: 22,
    combinedName: 'Philadelphia Flyers',
    largeLogo: Assets.icons.philadelphiaFlyersLarge.path,
    smallLogol: Assets.icons.philadelphiaFlyersSmall.path,
    primaryColor: '0xFFFA4616',
    secondaryColor: '0xFF010101',
    teamLocation: 'Philadelphia',
    teamName: 'Flyers',
    teamAbr: 'PHI',
  ),
  Team(
    id: 23,
    combinedName: 'Pittsburgh Penguins',
    largeLogo: Assets.icons.pittsburghPenguinsLarge.path,
    smallLogol: Assets.icons.pittsburghPenguinsSmall.path,
    primaryColor: '0xFFFFB81C',
    secondaryColor: '0xFF010101',
    teamLocation: 'Pittsburgh',
    teamName: 'Penguins',
    teamAbr: 'PIT',
  ),
  Team(
    id: 24,
    combinedName: 'San Jose Sharks',
    largeLogo: Assets.icons.sanJoseSharksLarge.path,
    smallLogol: Assets.icons.sanJoseSharksSmall.path,
    primaryColor: '0xFF006272',
    secondaryColor: '0xFFE57200',
    teamLocation: 'San Jose',
    teamName: 'Sharks',
    teamAbr: 'SJ',
  ),
  Team(
    id: 25,
    combinedName: 'Seattle Kraken',
    largeLogo: Assets.icons.seattleKrakenLarge.path,
    smallLogol: Assets.icons.seattleKrakenSmall.path,
    primaryColor: '0xFF001628',
    secondaryColor: '0xFF629EB5',
    teamLocation: 'Seattle',
    teamName: 'Kraken',
    teamAbr: 'SEA',
  ),
  Team(
    id: 26,
    combinedName: 'St. Louis Blues',
    largeLogo: Assets.icons.stLouisBluesLarge.path,
    smallLogol: Assets.icons.stLouisBluesSmall.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFFFB81C',
    teamLocation: 'St. Louis',
    teamName: 'Blues',
    teamAbr: 'STL',
  ),
  Team(
    id: 27,
    combinedName: 'Tampa Bay Lightning',
    largeLogo: Assets.icons.tampaBayLightningLarge.path,
    smallLogol: Assets.icons.tampaBayLightningSmall.path,
    primaryColor: '0xFF00205B',
    secondaryColor: '0xFFFFFFFF',
    teamLocation: 'Tampa Bay',
    teamName: 'Lightning',
    teamAbr: 'TB',
  ),
  Team(
    id: 28,
    combinedName: 'Toronto Maple Leafs',
    largeLogo: Assets.icons.torontoMapleLeafsLarge.path,
    smallLogol: Assets.icons.torontoMapleLeafsSmall.path,
    primaryColor: '0xFF00205B',
    secondaryColor: '0xFFFFFFFF',
    teamLocation: 'Toronto',
    teamName: 'Maple Leafs',
    teamAbr: 'TOR',
  ),
  Team(
    id: 29,
    combinedName: 'Vancouver Canucks',
    largeLogo: Assets.icons.vancouverCanucksLarge.path,
    smallLogol: Assets.icons.vancouverCanucksSmall.path,
    primaryColor: '0xFF00205B',
    secondaryColor: '0xFFFFFFFF',
    teamLocation: 'Vancouver',
    teamName: 'Canucks',
    teamAbr: 'VAN',
  ),
  Team(
    id: 30,
    combinedName: 'Vegas Golden Knights',
    largeLogo: Assets.icons.vegasGoldenKnightsLarge.path,
    smallLogol: Assets.icons.vegasGoldenKnightsSmall.path,
    primaryColor: '0xFFB9975B',
    secondaryColor: '0xFF333F48',
    teamLocation: 'Vegas',
    teamName: 'Golden Knights',
    teamAbr: 'VGK',
  ),
  Team(
    id: 31,
    combinedName: 'Washington Capitals',
    largeLogo: Assets.icons.washingtonCapitalsLarge.path,
    smallLogol: Assets.icons.washingtonCapitalsSmall.path,
    primaryColor: '0xFFC8102E',
    secondaryColor: '0xFF041E42',
    teamLocation: 'Washington',
    teamName: 'Capitals',
    teamAbr: 'WSH',
  ),
  Team(
    id: 32,
    combinedName: 'Winnipeg Jets',
    largeLogo: Assets.icons.winnipegJetsLarge.path,
    smallLogol: Assets.icons.winnipegJetsSmall.path,
    primaryColor: '0xFF041E42',
    secondaryColor: '0xFFFFFFFF',
    teamLocation: 'Winnipeg',
    teamName: 'Jets',
    teamAbr: 'WPG',
  ),
];
